//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CardComEntities1 : DbContext
    {
        public CardComEntities1()
            : base("name=CardComEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
    
        public virtual ObjectResult<GetClients_Result> GetClients()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClients_Result>("GetClients");
        }
    }
}
