//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public long ID { get; set; }
        public string CName { get; set; }
        public string CMail { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string Gender { get; set; }
        public string phone { get; set; }
    }
}
